- src/org/recompile/mobile/PlatformPlayer.java
> Close underlying MIDI player when deallocating audioplayer

- src/org/recompile/freej2me/FreeJ2ME.java
This adds basic numpad support. The numpad keys are mapped in a vertically inverted manner (1,2,3->7,8,9) and (7,8,9->1,2,3) as layout is vertically inverted in mobile phone keypads.
> Add numpad support

- src/org/recompile/freej2me/FreeJ2ME.java
Making small screen games look great (perfect square pixels) when resizing was painful. This adds a hotkey that let's you increase/decrease a global screen size multiplier. Also, scale can be specified from 4th CLI argument.
> Add integer window rescaling hotkeys

- src/org/recompile/freej2me/FreeJ2ME.java
- src/org/recompile/freej2me/RetroPie.java
- src/org/recompile/freej2me/ScreenShot.java
I modified the screenshot routine so that:
- It keeps it's exact same behavior for RetroPie users.
- For desktop version users, it creates a "screenshots" directory along the "rms" and "config" ones, and stores the screenshots there.
I bound it to the "C" key. Change it to whatever you feel convenient.
> Add screenshot support for desktop version

- src/javax/microedition/lcdui/Canvas.java
- src/javax/microedition/lcdui/Form.java
- src/javax/microedition/lcdui/List.java
- src/org/recompile/freej2me/Config.java
- src/org/recompile/freej2me/FreeJ2ME.java
- src/org/recompile/freej2me/Libretro.java
This implements the _Nokia Middle button_ softkey:
```
KEY_SOFTKEY3
public static final int KEY_SOFTKEY3
Key code constant for select key, middle softkey or second command button key. Not all devices have this key. The value is -5. 
```
for games that depend on it.
And modifies some other parts of FreeJ2ME to fully integrate the softkey.
WARNING / NOTE:
I modified javax.microedition.lcdui.Canvas replacing KEY_NUM5 with NOKIA_SOFT3. I'm not pretty sure of the correctness of this modification at all. I'm not sure what the behavior should be when phone is set to Nokia or Standard, since they appear to be harcoded to Nokia. :confused: . Shouldn't they be config-dependent?
> Implement Nokia Middle button keycode

- src/org/recompile/mobile/PlatformGraphics.java
This pull-request fixes issue #70 
**Before**
**After**
I took this code from [microemu implementation](https://github.com/tisoft/microemu/blob/master/microemulator/microemu-extensions/microemu-nokiaui/src/main/java/com/nokia/mid/ui/DirectGraphicsImp.java#L207) of `DirectGraphics` interface.
Maybe case of `TYPE_BYTE_1_GRAY` in `drawPixels(...)` method also should be fixed. But I have no game which uses this format.
> Fixed drawing of 1 bit image

- src/com/nokia/mid/m3d/M3D.java
1) Rewrote rotation matrix method. It is now possible to rotate around X axis. And Z axis, but it's never used in game. This patch fixed an issue when you can't look up or down in "look around" mode.
2) Rewrote projection matrix method. Nothing noticeable happen. I believe it's closer to "real" implementation now.
3) Fixed water draw method. It's hacky but looks like real one.
New issues:
1) When in "look around" mode turn all the way to the left (or right). Now turn up and down. You should notice a slight translation. It still can be a game bug.
2) Polygon clip algorithm has a minor issue. It clips some triangles which it shouldn't.
> Fixed some issues in Munkiki's Castles emulation

- .github/workflows/ant.yml
- README.md
Publish pre-built artifacts so that some people have `Java` but don't have `ant` can just download the `JAR` artifact and try it out.
> Publish build artifacts with Github Actions

- src/org/recompile/mobile/PlatformGraphics.java
Dialog box BG and water has intended alpha now, instead of black.
> Fix alpha in Bounce Tales

- src/sdl2/Makefile
The order in which the link options are placed in relation to the input files matter for certain linkers (gnu ld, for example)
GCC docs: https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html
Relevant excerpt:
> -llibrary
-l library
>[...]
>It makes a difference where in the command you write this option; the linker searches and processes libraries and object files in the order they are specified. Thus, ‘foo.o -lz bar.o’ searches library ‘z’ after file foo.o but before bar.o. If bar.o refers to functions in ‘z’, those functions may not be loaded. 
Interesting stack overflow question on the subject: https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc
> Fix SDL2 frontend build failure for linux relating to linker option order in Makefile 

- src/libretro/Makefile.common
https://github.com/hex007/freej2me/issues/93
> [FIX] wasm-ld: error: duplicate symbol: path_is_directory (#93)

- src/org/recompile/mobile/PlatformGraphics.java
Give your love to @vadosnaprimer please, who if nothing else took considerable verbal abuse while helping me work this out and did just as much if not more of the brain work part of this fix.
> fix #52 - Override parent version of `fillTriangle`

- src/org/recompile/freej2me/Config.java
- src/org/recompile/freej2me/FreeJ2ME.java
- src/org/recompile/freej2me/Libretro.java
- src/org/recompile/mobile/Mobile.java
6fa59b4 adds a Motorola keypad mode to the standard and libretro frontends (The most popular RAZR V3 keycode variant. If you're curious, I try to keep some of the other obscure variants Motorola used documented here https://github.com/Nokia64/J2ME-phone-quirks/blob/master/J2ME-phone-quirks.csv , using emulators and official docs as a reference. Any help is appreciated 😄)
4da1286 adds handling of the Siemens fire key. The constants were already defined at `org.recompile.mobile.Mobile` but it was left unused
a787565 adds the 132x176 resolution to the settings menu. Most games requiring the "Siemens" keypad mode usually work at this one. Decided to sneak it in here instead of opening another pull request for it, hope that's okay
> Motorola keypad suport and small fixes for Siemens devices

- src/org/recompile/mobile/PlatformGraphics.java
- src/org/recompile/mobile/PlatformImage.java
This fixes transformations 4 (`TRANS_MIRROR_ROT270`), 6 (`TRANS_ROT270`) and 7 (`TRANS_MIRROR_ROT90`) at `org.recompile.mobile.PlatformImage`, making the results match real devices.
> Fix PlatformImage.transformImage() transformations 4,6 and 7 (for #98 )

- src/javax/microedition/lcdui/Image.java
Improved the exception throwing done by the `javax.microedition.lcdui.Image.createImage()` methods for better compilance with the MIDP standard, fixes #89
Also, the "image from sub-image" createImage() method wasn't using the proper PlatformImage constructor leading to blank images or crashes instead
Before/after 9fa8df2 (_Cannonball_ by Bluette/wait4u)
> Image.createImage() exception throwing improvements and a tiny fix

- src/org/recompile/mobile/PlatformGraphics.java
Tiny fix for issue #122, calls to Graphics.translate(int x, int y) may have effects over the clip area values but they weren't being updated on FreeJ2ME's side causing issues on some games relying on reading back these values
EDIT: After testing some more games, I've noticed the first fix could cause a NullPointerException since Graphics2D.getClipBounds() may return null if the clip area had never been set. Added another commit on top, which instead updates the variables manually. Also the width and height never change so there's no need to update them
> Fix for #122

- src/javax/microedition/lcdui/Canvas.java
- src/org/recompile/mobile/PlatformGraphics.java
- src/org/recompile/mobile/PlatformImage.java
Fix for #124 (while keeping #61 happy)
Some games using DirectUtils.getDirectGraphics(Graphics g) rely on the underlying Graphics object of the returned DirectGraphics being the same across all calls to paint(), while FreeJ2ME was creating a new object per call
> Keep a same Graphics object for all paint() calls

- src/org/recompile/mobile/PlatformFont.java
respect more font properties
- Use SanSerif for SYSTEM and PROPORTIONAL but respect MONOSPACE
- Font style flags for bold and italics are the same, so pass the style flags to the awt font
- Check for the UNDERLINE style flag and apply the TextAttribute if present
> font-fixes

- src/org/recompile/freej2me/Libretro.java
Commits 463b516 and 6fa59b4 added support for Siemens and Motorola keycodes in the `getMobileKey` function of Libretro frontend (used for handling keyboard input), but the `getMobileKeyJoy` function which is used instead for handling the input from joypad devices was left unmodified leaving these unable to produce the newly introduced device-specific keycodes.
This small patch adds such support to the `getMobileKeyJoy` function.
> Add handling of Siemens and Motorola keycodes to Libretro getMobileKeyJoy()

- src/javax/microedition/lcdui/Canvas.java
- src/javax/microedition/lcdui/Displayable.java
- src/org/recompile/freej2me/Anbu.java
- src/org/recompile/freej2me/FreeJ2ME.java
- src/org/recompile/freej2me/Libretro.java
- src/org/recompile/mobile/MobilePlatform.java
This brings in the changes discussed at issue #130 plus the patch for the Libretro frontend, implemented in a similar fashion to the AWT one (I have _squashed_ the various intermediate work state commits from my repeat-events-support branch into three final per-frontend ones, for the sake of cleanness)
For now `hasRepeatEvents()` is harcoded to always return `true` as the three frontends do currently support them. May take a look later into making that per-frontend as per recompileorg's suggestions.
Hopefully this should solve quirks across many games... not introducing new ones 😅
Thank you!
> KeyRepeated event support

- src/libretro/freej2me_libretro.c
Previously, it had a tendency to close the entire frontend whenever a "Close Content" or "Restart" callback was issued, now only the core is closed, and a restart triggers a full core reload to allow the incoming core config options to be applied.
Decided to rename the branch since i'm thinking of pushing multiple PR's related to different parts of FreeJ2ME.
>  Improvements to the libretro core's shutdown and restart procedures. (renamed branch)

- src/libretro/freej2me_libretro.c
I'm not sure if those multiple Pull Requests will sit well with one another since i never tried doing something like this, but anyway...
The libretro core didn't have any input mapping exposed at all, so this PR should expose those, and also allow input remapping.
> Expose input mapping properties to the libretro core.

- src/javax/microedition/rms/RecordStore.java
This one fixes #152, at least partially. Pinball 3D Timeshock boots and saves rms data now... but some blind spots for the index on rms might still be present.
> Initial fix for possible negative index, might need something more down the line.

- src/javax/microedition/media/Manager.java
- src/org/recompile/mobile/PlatformPlayer.java
Taking a break from the libretro core improvements, this one improves the overall compatibility of FreeJ2ME. Many of the games i tested used different media types that actually are the same type as the ones currently implemented, which are "audio/midi" and "audio/x-wav", just worded differently. When situations like those happened, games either ignored the lack of support for the media and didn't play files of that type, or outright crashed. Some even crashed after the extra names were introduced, but i added a try-catch into the PlatformPlayer to deal with those as well.
This Pull Request aims at fixing most of the audio-related crashes that FreeJ2ME currently suffers (didn't face any related to audio anymore, more of a reason not to expose the audio config on the libretro frontend), …
> Improving the audio subsystem.

- src/org/recompile/freej2me/FreeJ2ME.java
Previously FreeJ2ME wouldn't apply resolutions passed as arguments because it would init a config file with the default res of 240x320 and update the main app with this default res, completely overriding the arguments received. This commit solves that, and also makes it so that the received args also override the resolution set in the config file, since those arguments still wouldn't apply in case a config file was already saved from a given app that was run with FreeJ2ME previously at a different res.
Fixes #165
> FreeJ2ME: Apply resolutions passed as commandline args.

- src/libretro/freej2me_libretro.c
- src/org/recompile/freej2me/Libretro.java
Related to #138. Calling that menu won't be necessary due to the frontend, and it also has the potential to freeze it if the user selects the "Exit" option.
> Libretro: Disable buttons that can call the built-in menu.

- src/javax/microedition/rms/RecordStore.java
- src/libretro/freej2me_libretro.c
- src/org/recompile/freej2me/Config.java
Previously the RA core would save configs incorrectly, now the folders are better organized, and the code was altered in a way that doesn't cause problems for the standalone versions of FreeJ2ME. Refer to #138 for more info about this.
~~Edit: Don't merge yet, just found a bug on DOOM II RPG through the libretro frontend.~~
Edit 2: Alright, now it should be fine.
> Improve FreeJ2ME's standalone and libretro core save paths.

- src/libretro/freej2me_libretro.c
- src/org/recompile/freej2me/FreeJ2ME.java
Fixes #156.
Edit: Fixes #158 as well.
Edit 2: Also related to #138.
Opted to unify both issues in a same PR because the game i tested for #158 also depends on #156 for screen rotation.
This PR now not only implements rotation on the AWT frontend, but also mouse drag events on it, and on libretro as well.
> Implement screen rotation on the AWT frontend, and add mouse drag events to both AWT and libretro.

- src/javax/microedition/pim/Contact.java
- src/javax/microedition/pim/ContactList.java
- src/javax/microedition/pim/Event.java
- src/javax/microedition/pim/EventList.java
- src/javax/microedition/pim/FieldEmptyException.java
- src/javax/microedition/pim/FieldFullException.java
- src/javax/microedition/pim/PIM.java
- src/javax/microedition/pim/PIMException.java
- src/javax/microedition/pim/PIMItem.java
- src/javax/microedition/pim/PIMList.java
- src/javax/microedition/pim/RepeatRule.java
- src/javax/microedition/pim/ToDo.java
- src/javax/microedition/pim/ToDoList.java
- src/javax/microedition/pim/UnsupportedFieldException.java
JSR 075 is composed of both FileConnect and PIM. FileConnect is being reviewed alongside bluetooth and obex over at #145, and adding even more files to that massive pull request isn't a good idea. Thankfully, PIM has no dependency on FileConnect, so it can be its own PR.
Fixes #155.
Edit: I see, yes i could have separated it into smaller units, but i figured having the whole PIM spec in one PR would be more organized. I'll try shortening the amount of files and changes in the next pull requests.
> Stubbing the rest of JSR 075 (PIM)

- README.md
Closes #176.
There wasn't any indication on how to build the libretro core. This change adds it and makes all build steps a bit clearer in general.
> Update README.md with clearer build instructions

- src/libretro/Makefile
- src/libretro/freej2me_libretro.c
- remove console window by using javaw
- allow use env `CC` to override gcc to use
> libretro Windows core minor fix

- src/org/recompile/mobile/PlatformPlayer.java
- src/org/recompile/mobile/WavImaAdpcmDecoder.java
Closes #149.
Copying message from commit:
In order to decode IMA ADPCM wav files, we first read the incoming wav's header and check if the reported Audio Format is '17', indicating that it is an IMA ADPCM stream. If it is, we begin to decode its samples into signed PCM16LE while maintaining the same amount of channels, and sampling rate. Once that is done, we build a new header for the decoded stream to reflect its new format and then send the completed stream back to PlatformPlayer's wavPlayer so it can handle it like a standard wav stream.
Additionally, a simple 'low-pass filter' was added to combat crackling on resulting samples, as it was really overbearing, it vastly improves quality at almost no cost.
> PlatformPlayer: Implement initial IMA ADPCM decoding support

- src/org/recompile/mobile/PlatformPlayer.java
Fixes #202 
Refer to that issue for more in-depth info. This one is rather rare, but there are apps which do indeed pass an audio stream to FreeJ2ME without providing its type, so we have to manually try and load them as one of the supported formats.
> PlatformPlayer: Attempt to load audio files with empty contentType

- src/org/recompile/mobile/PlatformPlayer.java
Fixes #200 
"Orcs and Elves" constantly tries to stop a MIDI stream that isn't even running, and ends up causing a stack overflow on PlatformPlayer. Since it only makes sense to stop streams that are actually running, add a check for cases where they aren't.
Since it has been shown to happen with MIDI streams, it might happen on WAV streams as well, so i'm adding that check for both.
> PlatformPlayer: Only stop media playback if it is running
